[package]
name = "lunar-logger"
version = "0.1.2"
edition = "2021"
repository = "https://github.com/Ciubix8513/lunar-logger"
license = "MIT"
description = "Simple logger with write to file functionality"
readme = "Readme.md"

[dependencies]
chrono = "0.4.38"
log = "0.4.21"
